// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetJson():Promise<Array<any>>;

export function SaveJson(arg1:any):Promise<boolean>;
